-- SFIA 8 Seed Data Part 3 - Delivery and Operation, Skills and Quality, Relationships

INSERT INTO benchmark_rates (
  skill_id, skill_name, skill_code, subcategory_id, category_id,
  sfia_level, tier_id, tier_name, day_rate, source, effective_date
) VALUES

-- ============================================================================
-- DELIVERY AND OPERATION (DO)
-- ============================================================================

-- NTAS - Network support (Levels 1-5) +10%
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 1, 'contractor', 'Contractor', 275, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 1, 'boutique', 'Boutique/SME', 360, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 1, 'mid', 'Mid-tier', 415, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 1, 'big4', 'Big 4/Global SI', 525, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 2, 'contractor', 'Contractor', 385, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 2, 'boutique', 'Boutique/SME', 500, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 2, 'mid', 'Mid-tier', 580, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 2, 'big4', 'Big 4/Global SI', 730, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 3, 'contractor', 'Contractor', 495, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 3, 'boutique', 'Boutique/SME', 645, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 3, 'mid', 'Mid-tier', 745, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 3, 'big4', 'Big 4/Global SI', 940, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 4, 'contractor', 'Contractor', 605, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 4, 'boutique', 'Boutique/SME', 785, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 4, 'mid', 'Mid-tier', 910, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 4, 'big4', 'Big 4/Global SI', 1150, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 5, 'contractor', 'Contractor', 770, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 5, 'boutique', 'Boutique/SME', 1000, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 5, 'mid', 'Mid-tier', 1155, 'UK Market Dec 2025', CURRENT_DATE),
('NTAS', 'Network support', 'NTAS', 'INFR', 'DO', 5, 'big4', 'Big 4/Global SI', 1465, 'UK Market Dec 2025', CURRENT_DATE),

-- ITOP - IT infrastructure (Levels 1-5)
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 1, 'contractor', 'Contractor', 250, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 1, 'boutique', 'Boutique/SME', 325, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 1, 'mid', 'Mid-tier', 375, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 1, 'big4', 'Big 4/Global SI', 475, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('ITOP', 'IT infrastructure', 'ITOP', 'INFR', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- DBAD - Database administration (Levels 2-5)
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('DBAD', 'Database administration', 'DBAD', 'INFR', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- USUP - Incident management (Levels 1-5)
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 1, 'contractor', 'Contractor', 250, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 1, 'boutique', 'Boutique/SME', 325, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 1, 'mid', 'Mid-tier', 375, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 1, 'big4', 'Big 4/Global SI', 475, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('USUP', 'Incident management', 'USUP', 'SVOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- PBMG - Problem management (Levels 3-6)
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('PBMG', 'Problem management', 'PBMG', 'SVOP', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- SCAD - Security administration (Levels 1-5)
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 1, 'contractor', 'Contractor', 275, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 1, 'boutique', 'Boutique/SME', 360, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 1, 'mid', 'Mid-tier', 415, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 1, 'big4', 'Big 4/Global SI', 525, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 2, 'contractor', 'Contractor', 385, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 2, 'boutique', 'Boutique/SME', 500, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 2, 'mid', 'Mid-tier', 580, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 2, 'big4', 'Big 4/Global SI', 730, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 3, 'contractor', 'Contractor', 495, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 3, 'boutique', 'Boutique/SME', 645, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 3, 'mid', 'Mid-tier', 745, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 3, 'big4', 'Big 4/Global SI', 940, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 4, 'contractor', 'Contractor', 605, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 4, 'boutique', 'Boutique/SME', 785, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 4, 'mid', 'Mid-tier', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1150, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 5, 'contractor', 'Contractor', 770, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 5, 'boutique', 'Boutique/SME', 1000, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 5, 'mid', 'Mid-tier', 1155, 'UK Market Dec 2025', CURRENT_DATE),
('SCAD', 'Security administration', 'SCAD', 'SEOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1465, 'UK Market Dec 2025', CURRENT_DATE),

-- THIN - Threat intelligence (Levels 3-6) +20%
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 3, 'contractor', 'Contractor', 540, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 3, 'boutique', 'Boutique/SME', 700, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 3, 'mid', 'Mid-tier', 810, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 3, 'big4', 'Big 4/Global SI', 1025, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 4, 'contractor', 'Contractor', 660, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 4, 'boutique', 'Boutique/SME', 860, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 4, 'mid', 'Mid-tier', 990, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1255, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 5, 'contractor', 'Contractor', 840, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 5, 'boutique', 'Boutique/SME', 1090, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 5, 'mid', 'Mid-tier', 1260, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1595, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 6, 'contractor', 'Contractor', 1080, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 6, 'boutique', 'Boutique/SME', 1405, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 6, 'mid', 'Mid-tier', 1620, 'UK Market Dec 2025', CURRENT_DATE),
('THIN', 'Threat intelligence', 'THIN', 'SEOP', 'DO', 6, 'big4', 'Big 4/Global SI', 2050, 'UK Market Dec 2025', CURRENT_DATE),

-- SLMO - Service level management (Levels 3-6)
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('SLMO', 'Service level management', 'SLMO', 'TECH', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- ============================================================================
-- SKILLS AND QUALITY (SQ)
-- ============================================================================

-- QUAS - Quality assurance (Levels 3-6)
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('QUAS', 'Quality assurance', 'QUAS', 'QUAL', 'SQ', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- TEAW - Technical writing (Levels 2-5) -15%
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 2, 'contractor', 'Contractor', 300, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 2, 'boutique', 'Boutique/SME', 390, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 2, 'mid', 'Mid-tier', 450, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 2, 'big4', 'Big 4/Global SI', 570, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 3, 'contractor', 'Contractor', 385, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 3, 'boutique', 'Boutique/SME', 500, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 3, 'mid', 'Mid-tier', 575, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 3, 'big4', 'Big 4/Global SI', 730, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 4, 'contractor', 'Contractor', 470, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 4, 'boutique', 'Boutique/SME', 610, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 4, 'mid', 'Mid-tier', 705, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 4, 'big4', 'Big 4/Global SI', 890, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 5, 'contractor', 'Contractor', 595, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 5, 'boutique', 'Boutique/SME', 775, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 5, 'mid', 'Mid-tier', 895, 'UK Market Dec 2025', CURRENT_DATE),
('TEAW', 'Technical writing', 'TEAW', 'KNOW', 'SQ', 5, 'big4', 'Big 4/Global SI', 1130, 'UK Market Dec 2025', CURRENT_DATE),

-- ============================================================================
-- RELATIONSHIPS AND ENGAGEMENT (RE)
-- ============================================================================

-- RLMT - Stakeholder relationship management (Levels 4-7)
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 7, 'contractor', 'Contractor', 1100, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 7, 'boutique', 'Boutique/SME', 1430, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 7, 'mid', 'Mid-tier', 1650, 'UK Market Dec 2025', CURRENT_DATE),
('RLMT', 'Stakeholder relationship management', 'RLMT', 'STKE', 'RE', 7, 'big4', 'Big 4/Global SI', 2090, 'UK Market Dec 2025', CURRENT_DATE),

-- CNSL - Consultancy (Levels 4-7)
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 7, 'contractor', 'Contractor', 1100, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 7, 'boutique', 'Boutique/SME', 1430, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 7, 'mid', 'Mid-tier', 1650, 'UK Market Dec 2025', CURRENT_DATE),
('CNSL', 'Consultancy', 'CNSL', 'STKE', 'RE', 7, 'big4', 'Big 4/Global SI', 2090, 'UK Market Dec 2025', CURRENT_DATE),

-- SUPM - Supplier management (Levels 3-6)
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('SUPM', 'Supplier management', 'SUPM', 'STKE', 'RE', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE);
