-- SFIA 8 Seed Data Part 5 - Remaining Delivery, Operations, Quality, and Other Skills

INSERT INTO benchmark_rates (
  skill_id, skill_name, skill_code, subcategory_id, category_id,
  sfia_level, tier_id, tier_name, day_rate, source, effective_date
) VALUES

-- ============================================================================
-- REMAINING DELIVERY AND OPERATION SKILLS
-- ============================================================================

-- ITMG - IT management (Levels 4-7)
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 7, 'contractor', 'Contractor', 1100, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 7, 'boutique', 'Boutique/SME', 1430, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 7, 'mid', 'Mid-tier', 1650, 'UK Market Dec 2025', CURRENT_DATE),
('ITMG', 'IT management', 'ITMG', 'TECH', 'DO', 7, 'big4', 'Big 4/Global SI', 2090, 'UK Market Dec 2025', CURRENT_DATE),

-- CPMG - Capacity management (Levels 3-6)
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('CPMG', 'Capacity management', 'CPMG', 'TECH', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- AVMT - Availability management (Levels 3-6)
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('AVMT', 'Availability management', 'AVMT', 'TECH', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- SVMG - Service management (Levels 3-6)
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('SVMG', 'Service management', 'SVMG', 'SVOP', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- CHMG - Change control (Levels 2-6)
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('CHMG', 'Change control', 'CHMG', 'SVOP', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- SEAC - Service acceptance (Levels 3-6)
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('SEAC', 'Service acceptance', 'SEAC', 'SVOP', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- STMG - Storage management (Levels 3-5)
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('STMG', 'Storage management', 'STMG', 'INFR', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- HWMG - Systems installation/decommissioning (Levels 1-5)
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 1, 'contractor', 'Contractor', 250, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 1, 'boutique', 'Boutique/SME', 325, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 1, 'mid', 'Mid-tier', 375, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 1, 'big4', 'Big 4/Global SI', 475, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('HWMG', 'Systems installation/decommissioning', 'HWMG', 'INFR', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- ASUP - Application support (Levels 2-5)
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('ASUP', 'Application support', 'ASUP', 'INFR', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- DCMA - Data centre facilities management (Levels 3-6)
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('DCMA', 'Data centre facilities management', 'DCMA', 'INFR', 'DO', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- VUAS - Vulnerability research (Levels 3-6) +20%
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 3, 'contractor', 'Contractor', 540, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 3, 'boutique', 'Boutique/SME', 700, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 3, 'mid', 'Mid-tier', 810, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 3, 'big4', 'Big 4/Global SI', 1025, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 4, 'contractor', 'Contractor', 660, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 4, 'boutique', 'Boutique/SME', 860, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 4, 'mid', 'Mid-tier', 990, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1255, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 5, 'contractor', 'Contractor', 840, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 5, 'boutique', 'Boutique/SME', 1090, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 5, 'mid', 'Mid-tier', 1260, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1595, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 6, 'contractor', 'Contractor', 1080, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 6, 'boutique', 'Boutique/SME', 1405, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 6, 'mid', 'Mid-tier', 1620, 'UK Market Dec 2025', CURRENT_DATE),
('VUAS', 'Vulnerability research', 'VUAS', 'SEOP', 'DO', 6, 'big4', 'Big 4/Global SI', 2050, 'UK Market Dec 2025', CURRENT_DATE),

-- DFOR - Digital forensics (Levels 3-6) +15%
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 3, 'contractor', 'Contractor', 520, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 3, 'boutique', 'Boutique/SME', 675, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 3, 'mid', 'Mid-tier', 780, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 3, 'big4', 'Big 4/Global SI', 985, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 4, 'contractor', 'Contractor', 635, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 4, 'boutique', 'Boutique/SME', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 4, 'mid', 'Mid-tier', 950, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1205, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 5, 'contractor', 'Contractor', 805, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 5, 'boutique', 'Boutique/SME', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 5, 'mid', 'Mid-tier', 1205, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1530, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 6, 'contractor', 'Contractor', 1035, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 6, 'boutique', 'Boutique/SME', 1345, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 6, 'mid', 'Mid-tier', 1555, 'UK Market Dec 2025', CURRENT_DATE),
('DFOR', 'Digital forensics', 'DFOR', 'SEOP', 'DO', 6, 'big4', 'Big 4/Global SI', 1965, 'UK Market Dec 2025', CURRENT_DATE),

-- SCOP - Security operations (Levels 2-6)
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 2, 'contractor', 'Contractor', 385, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 2, 'boutique', 'Boutique/SME', 500, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 2, 'mid', 'Mid-tier', 580, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 2, 'big4', 'Big 4/Global SI', 730, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 3, 'contractor', 'Contractor', 495, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 3, 'boutique', 'Boutique/SME', 645, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 3, 'mid', 'Mid-tier', 745, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 3, 'big4', 'Big 4/Global SI', 940, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 4, 'contractor', 'Contractor', 605, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 4, 'boutique', 'Boutique/SME', 785, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 4, 'mid', 'Mid-tier', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 4, 'big4', 'Big 4/Global SI', 1150, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 5, 'contractor', 'Contractor', 770, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 5, 'boutique', 'Boutique/SME', 1000, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 5, 'mid', 'Mid-tier', 1155, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 5, 'big4', 'Big 4/Global SI', 1465, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 6, 'contractor', 'Contractor', 990, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 6, 'boutique', 'Boutique/SME', 1285, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 6, 'mid', 'Mid-tier', 1485, 'UK Market Dec 2025', CURRENT_DATE),
('SCOP', 'Security operations', 'SCOP', 'SEOP', 'DO', 6, 'big4', 'Big 4/Global SI', 1880, 'UK Market Dec 2025', CURRENT_DATE);
