-- SFIA 8 Seed Data Part 4 - Remaining skills to complete all 97

INSERT INTO benchmark_rates (
  skill_id, skill_name, skill_code, subcategory_id, category_id,
  sfia_level, tier_id, tier_name, day_rate, source, effective_date
) VALUES

-- ============================================================================
-- REMAINING STRATEGY AND ARCHITECTURE SKILLS
-- ============================================================================

-- BUSA - Business strategy and planning (Levels 5-7)
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 7, 'contractor', 'Contractor', 1100, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 7, 'boutique', 'Boutique/SME', 1430, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 7, 'mid', 'Mid-tier', 1650, 'UK Market Dec 2025', CURRENT_DATE),
('BUSA', 'Business strategy and planning', 'BUSA', 'STRT', 'SA', 7, 'big4', 'Big 4/Global SI', 2090, 'UK Market Dec 2025', CURRENT_DATE),

-- DEMM - Demand management (Levels 4-6)
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('DEMM', 'Demand management', 'DEMM', 'STRT', 'SA', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- FMIT - Financial management (Levels 4-6)
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('FMIT', 'Financial management', 'FMIT', 'GOVR', 'SA', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- INAS - Information assurance (Levels 3-6)
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('INAS', 'Information assurance', 'INAS', 'SECU', 'SA', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- VISL - Data visualisation (Levels 2-5)
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('VISL', 'Data visualisation', 'VISL', 'INFO', 'SA', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- ============================================================================
-- REMAINING CHANGE AND TRANSFORMATION SKILLS
-- ============================================================================

-- POMG - Portfolio management (Levels 5-7)
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 7, 'contractor', 'Contractor', 1100, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 7, 'boutique', 'Boutique/SME', 1430, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 7, 'mid', 'Mid-tier', 1650, 'UK Market Dec 2025', CURRENT_DATE),
('POMG', 'Portfolio management', 'POMG', 'CHPM', 'CT', 7, 'big4', 'Big 4/Global SI', 2090, 'UK Market Dec 2025', CURRENT_DATE),

-- BENM - Benefits management (Levels 4-6)
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('BENM', 'Benefits management', 'BENM', 'CHPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- BPRE - Business process improvement (Levels 3-6)
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('BPRE', 'Business process improvement', 'BPRE', 'BAPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- URCH - User research (Levels 3-6)
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('URCH', 'User research', 'URCH', 'UXPD', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- INCA - Content design (Levels 2-5)
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('INCA', 'Content design', 'INCA', 'UXPD', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),

-- ============================================================================
-- REMAINING DEVELOPMENT AND IMPLEMENTATION SKILLS
-- ============================================================================

-- DESN - Systems design (Levels 3-6)
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('DESN', 'Systems design', 'DESN', 'SYSD', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- SWDN - Software design (Levels 3-6)
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('SWDN', 'Software design', 'SWDN', 'SYSD', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- SINT - Systems integration and build (Levels 2-6)
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('SINT', 'Systems integration and build', 'SINT', 'SDLC', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- CFMG - Configuration management (Levels 2-6)
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('CFMG', 'Configuration management', 'CFMG', 'SDLC', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- DLMG - Systems and software life cycle engineering (Levels 4-6)
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('DLMG', 'Systems and software life cycle engineering', 'DLMG', 'SDLC', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- PORT - Porting/software configuration (Levels 2-5)
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('PORT', 'Porting/software configuration', 'PORT', 'SDLC', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE);
