-- SFIA 8 Seed Data Part 2 - Change and Transformation, Development and Implementation

INSERT INTO benchmark_rates (
  skill_id, skill_name, skill_code, subcategory_id, category_id,
  sfia_level, tier_id, tier_name, day_rate, source, effective_date
) VALUES

-- ============================================================================
-- CHANGE AND TRANSFORMATION (CT)
-- ============================================================================

-- PRMG - Project management (Levels 3-7)
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 3, 'contractor', 'Contractor', 475, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 3, 'boutique', 'Boutique/SME', 615, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 3, 'mid', 'Mid-tier', 710, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 3, 'big4', 'Big 4/Global SI', 900, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 4, 'contractor', 'Contractor', 575, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 4, 'boutique', 'Boutique/SME', 750, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 4, 'mid', 'Mid-tier', 865, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 4, 'big4', 'Big 4/Global SI', 1095, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 5, 'contractor', 'Contractor', 735, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 5, 'boutique', 'Boutique/SME', 955, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 5, 'mid', 'Mid-tier', 1100, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1395, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 6, 'contractor', 'Contractor', 945, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 6, 'boutique', 'Boutique/SME', 1230, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 6, 'mid', 'Mid-tier', 1420, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1795, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 7, 'contractor', 'Contractor', 1155, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 7, 'boutique', 'Boutique/SME', 1500, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 7, 'mid', 'Mid-tier', 1730, 'UK Market Dec 2025', CURRENT_DATE),
('PRMG', 'Project management', 'PRMG', 'CHPM', 'CT', 7, 'big4', 'Big 4/Global SI', 2195, 'UK Market Dec 2025', CURRENT_DATE),

-- PGMG - Programme management (Levels 5-7) +15%
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 5, 'contractor', 'Contractor', 805, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 5, 'boutique', 'Boutique/SME', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 5, 'mid', 'Mid-tier', 1205, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1530, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 6, 'contractor', 'Contractor', 1035, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 6, 'boutique', 'Boutique/SME', 1345, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 6, 'mid', 'Mid-tier', 1555, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1965, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 7, 'contractor', 'Contractor', 1265, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 7, 'boutique', 'Boutique/SME', 1645, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 7, 'mid', 'Mid-tier', 1900, 'UK Market Dec 2025', CURRENT_DATE),
('PGMG', 'Programme management', 'PGMG', 'CHPM', 'CT', 7, 'big4', 'Big 4/Global SI', 2405, 'UK Market Dec 2025', CURRENT_DATE),

-- CIPM - Organisational change management (Levels 4-6)
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('CIPM', 'Organisational change management', 'CIPM', 'CHPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- BUAN - Business analysis (Levels 3-6)
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('BUAN', 'Business analysis', 'BUAN', 'BAPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- REQM - Requirements definition and management (Levels 2-6)
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('REQM', 'Requirements definition and management', 'REQM', 'BAPM', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- HCEV - User experience design (Levels 2-6)
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('HCEV', 'User experience design', 'HCEV', 'UXPD', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- PROD - Product management (Levels 3-6)
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('PROD', 'Product management', 'PROD', 'UXPD', 'CT', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- ============================================================================
-- DEVELOPMENT AND IMPLEMENTATION (DI)
-- ============================================================================

-- ARCH - Solution architecture (Levels 4-6) +15%
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 4, 'contractor', 'Contractor', 635, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 4, 'boutique', 'Boutique/SME', 825, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 4, 'mid', 'Mid-tier', 950, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 4, 'big4', 'Big 4/Global SI', 1205, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 5, 'contractor', 'Contractor', 805, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 5, 'boutique', 'Boutique/SME', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 5, 'mid', 'Mid-tier', 1205, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 5, 'big4', 'Big 4/Global SI', 1530, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 6, 'contractor', 'Contractor', 1035, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 6, 'boutique', 'Boutique/SME', 1345, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 6, 'mid', 'Mid-tier', 1555, 'UK Market Dec 2025', CURRENT_DATE),
('ARCH', 'Solution architecture', 'ARCH', 'SYSD', 'DI', 6, 'big4', 'Big 4/Global SI', 1965, 'UK Market Dec 2025', CURRENT_DATE),

-- NTDS - Network design (Levels 3-6) +10%
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 3, 'contractor', 'Contractor', 495, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 3, 'boutique', 'Boutique/SME', 645, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 3, 'mid', 'Mid-tier', 745, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 3, 'big4', 'Big 4/Global SI', 940, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 4, 'contractor', 'Contractor', 605, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 4, 'boutique', 'Boutique/SME', 785, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 4, 'mid', 'Mid-tier', 910, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 4, 'big4', 'Big 4/Global SI', 1150, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 5, 'contractor', 'Contractor', 770, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 5, 'boutique', 'Boutique/SME', 1000, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 5, 'mid', 'Mid-tier', 1155, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 5, 'big4', 'Big 4/Global SI', 1465, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 6, 'contractor', 'Contractor', 990, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 6, 'boutique', 'Boutique/SME', 1285, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 6, 'mid', 'Mid-tier', 1485, 'UK Market Dec 2025', CURRENT_DATE),
('NTDS', 'Network design', 'NTDS', 'SYSD', 'DI', 6, 'big4', 'Big 4/Global SI', 1880, 'UK Market Dec 2025', CURRENT_DATE),

-- DBDS - Database design (Levels 3-6)
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('DBDS', 'Database design', 'DBDS', 'SYSD', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- PROG - Programming/software development (Levels 2-6)
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 2, 'contractor', 'Contractor', 350, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 2, 'boutique', 'Boutique/SME', 455, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 2, 'mid', 'Mid-tier', 525, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 2, 'big4', 'Big 4/Global SI', 665, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('PROG', 'Programming/software development', 'PROG', 'SDLC', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- TEST - Testing (Levels 1-6) -5%
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 1, 'contractor', 'Contractor', 240, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 1, 'boutique', 'Boutique/SME', 310, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 1, 'mid', 'Mid-tier', 360, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 1, 'big4', 'Big 4/Global SI', 455, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 2, 'contractor', 'Contractor', 335, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 2, 'boutique', 'Boutique/SME', 435, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 2, 'mid', 'Mid-tier', 500, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 2, 'big4', 'Big 4/Global SI', 635, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 3, 'contractor', 'Contractor', 430, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 3, 'boutique', 'Boutique/SME', 560, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 3, 'mid', 'Mid-tier', 645, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 3, 'big4', 'Big 4/Global SI', 815, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 4, 'contractor', 'Contractor', 525, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 4, 'boutique', 'Boutique/SME', 680, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 4, 'mid', 'Mid-tier', 785, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 4, 'big4', 'Big 4/Global SI', 995, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 5, 'contractor', 'Contractor', 665, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 5, 'boutique', 'Boutique/SME', 865, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 5, 'mid', 'Mid-tier', 1000, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 5, 'big4', 'Big 4/Global SI', 1265, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 6, 'contractor', 'Contractor', 855, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 6, 'boutique', 'Boutique/SME', 1110, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 6, 'mid', 'Mid-tier', 1285, 'UK Market Dec 2025', CURRENT_DATE),
('TEST', 'Testing', 'TEST', 'SDLC', 'DI', 6, 'big4', 'Big 4/Global SI', 1625, 'UK Market Dec 2025', CURRENT_DATE),

-- RELM - Release and deployment (Levels 3-6)
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('RELM', 'Release and deployment', 'RELM', 'SDLC', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE),

-- DATS - Data science (Levels 3-6) +20%
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 3, 'contractor', 'Contractor', 540, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 3, 'boutique', 'Boutique/SME', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 3, 'mid', 'Mid-tier', 810, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 3, 'big4', 'Big 4/Global SI', 1025, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 4, 'contractor', 'Contractor', 660, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 4, 'boutique', 'Boutique/SME', 860, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 4, 'mid', 'Mid-tier', 990, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 4, 'big4', 'Big 4/Global SI', 1255, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 5, 'contractor', 'Contractor', 840, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 5, 'boutique', 'Boutique/SME', 1090, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 5, 'mid', 'Mid-tier', 1260, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 5, 'big4', 'Big 4/Global SI', 1595, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 6, 'contractor', 'Contractor', 1080, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 6, 'boutique', 'Boutique/SME', 1405, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 6, 'mid', 'Mid-tier', 1620, 'UK Market Dec 2025', CURRENT_DATE),
('DATS', 'Data science', 'DATS', 'DATA', 'DI', 6, 'big4', 'Big 4/Global SI', 2050, 'UK Market Dec 2025', CURRENT_DATE),

-- MLNG - Machine learning (Levels 3-6) +25%
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 3, 'contractor', 'Contractor', 565, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 3, 'boutique', 'Boutique/SME', 735, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 3, 'mid', 'Mid-tier', 845, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 3, 'big4', 'Big 4/Global SI', 1070, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 4, 'contractor', 'Contractor', 690, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 4, 'boutique', 'Boutique/SME', 895, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 4, 'mid', 'Mid-tier', 1035, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 4, 'big4', 'Big 4/Global SI', 1310, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 5, 'contractor', 'Contractor', 875, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 5, 'boutique', 'Boutique/SME', 1140, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 5, 'mid', 'Mid-tier', 1315, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 5, 'big4', 'Big 4/Global SI', 1665, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 6, 'contractor', 'Contractor', 1125, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 6, 'boutique', 'Boutique/SME', 1465, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 6, 'mid', 'Mid-tier', 1690, 'UK Market Dec 2025', CURRENT_DATE),
('MLNG', 'Machine learning', 'MLNG', 'DATA', 'DI', 6, 'big4', 'Big 4/Global SI', 2140, 'UK Market Dec 2025', CURRENT_DATE),

-- DENG - Data engineering (Levels 3-6)
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 3, 'contractor', 'Contractor', 450, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 3, 'boutique', 'Boutique/SME', 585, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 3, 'mid', 'Mid-tier', 675, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 3, 'big4', 'Big 4/Global SI', 855, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 4, 'contractor', 'Contractor', 550, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 4, 'boutique', 'Boutique/SME', 715, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 4, 'mid', 'Mid-tier', 825, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 4, 'big4', 'Big 4/Global SI', 1045, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 5, 'contractor', 'Contractor', 700, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 5, 'boutique', 'Boutique/SME', 910, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 5, 'mid', 'Mid-tier', 1050, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 5, 'big4', 'Big 4/Global SI', 1330, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 6, 'contractor', 'Contractor', 900, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 6, 'boutique', 'Boutique/SME', 1170, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 6, 'mid', 'Mid-tier', 1350, 'UK Market Dec 2025', CURRENT_DATE),
('DENG', 'Data engineering', 'DENG', 'DATA', 'DI', 6, 'big4', 'Big 4/Global SI', 1710, 'UK Market Dec 2025', CURRENT_DATE);
